### ISSUE TITLE
Addon is broken in ruRU locale

### ISSUE THREAD

**Issue by RENgOLD** [Anonomit/ZeraTooltip#5]
Addon works until 2.18 update. Now works only reforge, ilvl and enchant strings replace:
with addon:
![image](https://github.com/Anonomit/ZeraTooltip/assets/1100128/63066156-252c-405a-ae5c-4cef313dc548)

without:
![image](https://github.com/Anonomit/ZeraTooltip/assets/1100128/4dbaa7c7-c276-43d3-bcd0-c9247d72711c)

**Comment by Anonomit** [comment]
Whoops, looks like I broke the automatic portion of localization when I was moving that stuff around. It's trying to recognize the English Globalstrings instead of the localized ones. I'll get that fixed today.

**Comment by Anonomit** [comment]
Should be working fine now. Thanks for the report.
