### ISSUE TITLE
Broken tooltips of reforged set items

### ISSUE THREAD

**Issue by RENgOLD** [Anonomit/ZeraTooltip#6]
Broken reforged set items (probably in non-english locale).
![image](https://github.com/Anonomit/ZeraTooltip/assets/1100128/45064875-3bf8-4664-8e68-e42d06b0435d)

For example, same t11 shoulders but not reforged:
![image](https://github.com/Anonomit/ZeraTooltip/assets/1100128/96e84300-5b4e-41a8-89db-ec378484c818)

**Comment by Anonomit** [comment]
I'm working on this. It only happens when you look at two copies of the same item consecutively which have an identical item link. In the meantime, you could avoid the issue by looking at a different tooltip in between those two items.
